apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service-depl-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-service
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
        - name: events-service
          image: sherpa/events-service:0.0.1
          env:
            - name: DATABASE_URL
              value: 'postgresql://postgres:admin@events-service-clusterip-postgres-srv:5432/postgres'
            - name: NODE_ENV
              value: 'development'
            - name: PORT
              value: '9000'
            - name: KAFKA_GROUP_ID
              value: 'events-service-group'
            - name: KAFKA_TOPIC
              value: 'events'
            - name: KAFKA_CLIENT_ID
              value: 'events-service-client'
            - name: KAFKA_BROKERS
              value: 'kafka-clusterip-srv:9092'
---
apiVersion: v1
kind: Service
metadata:
  name: events-service-nodeport-srv-dev
spec:
  type: NodePort
  selector:
    app: events-service
  ports:
    - name: events-service
      port: 9000
      targetPort: 9000
