apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-uploader-service-postgres-depl-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-uploader-service-postgres
  template:
    metadata:
      labels:
        app: file-uploader-service-postgres
    spec:
      containers:
        - name: file-uploader-service-postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: 'admin'
---
apiVersion: v1
kind: Service
metadata:
  name: file-uploader-service-clusterip-postgres-srv
spec:
  selector:
    app: file-uploader-service-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
